name: gfwlist2dnsmasq

on:
    push:
        branches:
            - main

jobs:
    my-job:
        name: My Job
        runs-on: ubuntu-latest
        steps:
        -   name: install git curl wget
            run: sudo apt update && sudo apt install -y git curl wget
      