name: gfwlist2dnsmasq

on:
    push:
        branches:
            - main
    schedule:
    - cron: "0 2 * * *"

jobs:
    my-job:
        name: My Job
        runs-on: ubuntu-latest
        steps:
        -   name: install git curl wget
            run: sudo apt update && sudo apt install -y git curl wget
        -   name: Checkout
            uses: actions/checkout@main
        -   name: Build GFW
            run: mkdir -p public && cd public && wget https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh && chmod +x ./gfwlist2dnsmasq.sh && ./gfwlist2dnsmasq.sh -o ./gfw.conf
        -   name: Build China List
            run: mkdir -p public && cd public && wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf -o china.conf
        -   name: Deploy to GitHub Pages
            if: success()
            uses: crazy-max/ghaction-github-pages@v3
            with:
                target_branch: gh-pages
                build_dir: public
            env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      